# Generated by Django 5.1.1 on 2024-11-21 20:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('refugio_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='perrito',
            old_name='edad',
            new_name='años',
        ),
    ]
